import type { Metadata } from "next";
import Link from "next/link";
import { isValidLocale } from "@/i18n/config";
import type { Locale } from "@/i18n/config";

export const metadata: Metadata = {
  title: "AI Agents Write Code — Who Verifies It? | Vigil Blog",
  description:
    "AI coding agents ship PRs in minutes. But confidence in the description doesn't mean accuracy in the diff. Here's why verification is the missing layer.",
};

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-xl font-semibold text-text-primary mt-12 mb-4">{children}</h2>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-text-secondary leading-relaxed mb-4">{children}</p>;
}

function Highlight({ children }: { children: React.ReactNode }) {
  return (
    <div className="border-l-2 border-accent pl-4 my-6">
      <p className="text-text-primary font-medium">{children}</p>
    </div>
  );
}

const content = {
  en: {
    title: "AI Agents Write Code — Who Verifies It?",
    date: "March 24, 2026",
    readTime: "4 min read",
    backLabel: "← Back to blog",
    sections: [
      {
        heading: "The speed is real. The trust gap is growing.",
        paragraphs: [
          "Claude Code, Cursor, Devin, GitHub Copilot Workspace — AI coding agents are shipping pull requests in minutes. Complete with confident descriptions: \"Adds auth middleware.\" \"Fixes the timeout bug.\" \"No breaking changes.\"",
          "But here's the thing nobody talks about: these descriptions are generated by the same model that wrote the code. The agent believes what it wrote is correct. The description reflects that confidence, not an independent assessment.",
          "You now have a PR that reads perfectly, looks professional, and might be completely wrong about what it actually does.",
        ],
      },
      {
        heading: "CI doesn't solve this",
        paragraphs: [
          "CI tells you if code compiles and tests pass. It doesn't tell you if the PR description matches the diff. A PR can say \"adds rate limiting\" while the diff actually adds rate limiting AND silently changes the database connection pool size. CI passes. The reviewer skims the description. The hidden change ships.",
          "Code review tools like CodeRabbit analyze code quality — style, bugs, best practices. They don't verify claims. They don't check if what the PR says matches what the code does.",
        ],
      },
      {
        heading: "The verification layer",
        paragraphs: [
          "What's missing is a system that reads the PR description, extracts every claim, and verifies each one against the actual diff. Then scans for everything the description didn't mention.",
          "That's what Vigil does. It reads your PR title and body, extracts claims like \"adds auth middleware\" and \"fixes timeout,\" then checks the diff to confirm or contradict each one. It also surfaces undocumented changes — new dependencies, environment variables, schema modifications that nobody mentioned.",
        ],
      },
      {
        heading: "Why this matters now",
        paragraphs: [
          "When humans wrote all the code, the PR author usually knew what they changed. The description was often incomplete but rarely misleading. With AI agents, the description is always confident and sometimes wrong.",
          "The faster code gets written, the more you need an independent verification layer. Not to replace code review — to complement it with a truthfulness check that nobody has time to do manually at scale.",
        ],
      },
    ],
    cta: "Try Vigil on your next AI-generated PR →",
  },
  es: {
    title: "Los agentes de IA escriben código — ¿quién lo verifica?",
    date: "24 de marzo, 2026",
    readTime: "4 min de lectura",
    backLabel: "← Volver al blog",
    sections: [
      {
        heading: "La velocidad es real. La brecha de confianza crece.",
        paragraphs: [
          "Claude Code, Cursor, Devin, GitHub Copilot Workspace — los agentes de IA están creando pull requests en minutos. Con descripciones seguras: \"Agrega middleware de auth.\" \"Corrige el bug de timeout.\" \"Sin breaking changes.\"",
          "Pero hay algo de lo que nadie habla: estas descripciones las genera el mismo modelo que escribió el código. El agente cree que lo que escribió es correcto. La descripción refleja esa confianza, no una evaluación independiente.",
          "Ahora tienes un PR que se lee perfecto, se ve profesional, y podría estar completamente equivocado sobre lo que realmente hace.",
        ],
      },
      {
        heading: "CI no resuelve esto",
        paragraphs: [
          "CI te dice si el código compila y los tests pasan. No te dice si la descripción del PR coincide con el diff. Un PR puede decir \"agrega rate limiting\" mientras el diff agrega rate limiting Y silenciosamente cambia el pool de conexiones a la base de datos. CI pasa. El reviewer ojea la descripción. El cambio oculto llega a producción.",
          "Herramientas de code review como CodeRabbit analizan calidad de código — estilo, bugs, buenas prácticas. No verifican claims. No revisan si lo que dice el PR coincide con lo que hace el código.",
        ],
      },
      {
        heading: "La capa de verificación",
        paragraphs: [
          "Lo que falta es un sistema que lea la descripción del PR, extraiga cada afirmación, y verifique cada una contra el diff real. Y luego escanee todo lo que la descripción no mencionó.",
          "Eso es lo que hace Vigil. Lee el título y cuerpo de tu PR, extrae claims como \"agrega middleware de auth\" y \"corrige timeout,\" y luego revisa el diff para confirmar o contradecir cada uno. También detecta cambios no documentados — dependencias nuevas, variables de entorno, modificaciones de schema que nadie mencionó.",
        ],
      },
      {
        heading: "Por qué importa ahora",
        paragraphs: [
          "Cuando los humanos escribían todo el código, el autor del PR generalmente sabía qué cambió. La descripción era a menudo incompleta pero rara vez engañosa. Con agentes de IA, la descripción siempre es segura y a veces incorrecta.",
          "Mientras más rápido se escribe código, más necesitas una capa de verificación independiente. No para reemplazar el code review — para complementarlo con una verificación de veracidad que nadie tiene tiempo de hacer manualmente a escala.",
        ],
      },
    ],
    cta: "Prueba Vigil en tu próximo PR generado por IA →",
  },
};

export default async function AiVerificationPost({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: localeParam } = await params;
  const locale: Locale = isValidLocale(localeParam) ? localeParam : "en";
  const t = content[locale];

  return (
    <article className="mx-auto max-w-[720px] px-6 py-16 sm:py-24">
      <Link href={`/${locale}/blog`} className="text-sm text-text-muted hover:text-accent transition-colors">
        {t.backLabel}
      </Link>
      <h1 className="text-2xl sm:text-3xl font-semibold text-text-primary mt-6 mb-2">{t.title}</h1>
      <div className="flex items-center gap-3 text-xs text-text-muted mb-12">
        <time>{t.date}</time>
        <span>·</span>
        <span>{t.readTime}</span>
      </div>

      {t.sections.map((section, i) => (
        <div key={i}>
          <H2>{section.heading}</H2>
          {section.paragraphs.map((p, j) => (
            <P key={j}>{p}</P>
          ))}
        </div>
      ))}

      <Highlight>
        {locale === "en"
          ? "Code is becoming commodity. Trust is becoming scarce. Verification is the layer that bridges the gap."
          : "El código se está volviendo commodity. La confianza es cada vez más escasa. La verificación es la capa que cierra la brecha."}
      </Highlight>

      <div className="mt-12 text-center">
        <a
          href="https://github.com/apps/keepvigil"
          className="inline-flex items-center gap-2 px-6 py-3 rounded-[6px] text-sm font-medium bg-accent text-[#080d1a] hover:bg-accent-hover transition-colors"
        >
          {t.cta}
        </a>
      </div>
    </article>
  );
}
